import {
  pgTable,
  varchar,
  text,
  integer,
  boolean,
  timestamp,
  real,
  date,
  uuid,
} from "drizzle-orm/pg-core";

// ================================
// TABEL ADMIN / PANITIA DIKLAT
// ================================
export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  role: varchar("role", { length: 20 }).notNull().default("admin"),
  fullName: varchar("full_name", { length: 255 }).notNull(),
  email: varchar("email", { length: 255 }),
  password: varchar("password", { length: 255 }),
  phoneNumber: varchar("phone_number", { length: 30 }),
  schoolOrigin: varchar("school_origin", { length: 255 }),
  age: integer("age"),
  address: text("address"),
  placeOfBirth: varchar("place_of_birth", { length: 255 }),
  dateOfBirth: varchar("date_of_birth", { length: 20 }),
  homeAddress: text("home_address"),
  institutionName: varchar("institution_name", { length: 255 }),
  studyProgram: varchar("study_program", { length: 255 }),
  semester: integer("semester"),
  practiceStartDate: varchar("practice_start_date", { length: 20 }),
  practiceEndDate: varchar("practice_end_date", { length: 20 }),
  practiceDurationWeeks: integer("practice_duration_weeks"),
  stase: varchar("stase", { length: 100 }),
  staseLainnya: varchar("stase_lainnya", { length: 100 }),
  diplomaFile: text("diploma_file"),
  isActive: boolean("is_active").notNull().default(true),
  isDeleted: boolean("is_deleted").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ================================
// TABEL SEMINAR / EVENT
// ================================
export const seminars = pgTable("seminars", {
  id: uuid("id").primaryKey().defaultRandom(),
  title: varchar("title", { length: 255 }).notNull(),
  description: text("description"),
  date: date("date").notNull(),
  startTime: varchar("start_time", { length: 10 }),
  endTime: varchar("end_time", { length: 10 }),
  location: varchar("location", { length: 255 }),
  maxParticipants: integer("max_participants").default(0),
  useQr: boolean("use_qr").notNull().default(true),
  useFace: boolean("use_face").notNull().default(true),
  useManual: boolean("use_manual").notNull().default(false),
  presensiOpen: boolean("presensi_open").notNull().default(false),
  isActive: boolean("is_active").notNull().default(true),
  isCompleted: boolean("is_completed").notNull().default(false),
  isDeleted: boolean("is_deleted").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ================================
// TABEL PENDAFTARAN PESERTA
// ================================
export const registrations = pgTable("registrations", {
  id: uuid("id").primaryKey().defaultRandom(),
  seminarId: uuid("seminar_id")
    .notNull()
    .references(() => seminars.id),
  fullName: varchar("full_name", { length: 255 }).notNull(),
  email: varchar("email", { length: 255 }),
  phoneNumber: varchar("phone_number", { length: 30 }),
  institution: varchar("institution", { length: 255 }),
  profession: varchar("profession", { length: 100 }),
  qrCode: varchar("qr_code", { length: 255 }),
  isPresent: boolean("is_present").notNull().default(false),
  presentTime: timestamp("present_time"),
  presentMethod: varchar("present_method", { length: 20 }),
  certificateSent: boolean("certificate_sent").notNull().default(false),
  certificateNumber: integer("certificate_number"),
  certificateCode: varchar("certificate_code", { length: 255 }),
  certificateGeneratedAt: timestamp("certificate_generated_at"),
  isDeleted: boolean("is_deleted").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ================================
// FACE EMBEDDINGS (Face ID Descriptors)
// ================================
// Stores 128D face descriptors generated by face-api.js FaceNet.
// One registration can have multiple descriptors (for re-enrollment).
export const faceEmbeddings = pgTable("face_embeddings", {
  id: uuid("id").primaryKey().defaultRandom(),
  registrationId: uuid("registration_id")
    .notNull()
    .references(() => registrations.id),
  descriptor: text("descriptor").notNull(), // JSON array of 128 floats
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ================================
// SERTIFIKAT
// ================================
export const certificates = pgTable("certificates", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull(),
  templateId: uuid("template_id"),
  title: varchar("title", { length: 255 }).notNull(),
  issuanceDate: varchar("issuance_date", { length: 50 }),
  fileUrl: varchar("file_url", { length: 500 }),
  generatedDate: timestamp("generated_date"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  isDeleted: boolean("is_deleted").notNull().default(false),
  certificateNumber: varchar("certificate_number", { length: 255 }),
});

// ================================
// PRESENSI / ATTENDANCE
// ================================
export const attendance = pgTable("attendance", {
  id: uuid("id").primaryKey().defaultRandom(),
  registrationId: uuid("registration_id")
    .notNull()
    .references(() => registrations.id),
  method: varchar("method", { length: 20 }).notNull(), // face, qr, code
  timestamp: timestamp("timestamp").notNull().defaultNow(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ================================
// PEMATERI / SPEAKER
// ================================
export const speakers = pgTable("speakers", {
  id: uuid("id").primaryKey().defaultRandom(),
  seminarId: uuid("seminar_id")
    .notNull()
    .references(() => seminars.id),
  name: varchar("name", { length: 255 }).notNull(),
  topic: text("topic"),
  displayOrder: integer("display_order").notNull().default(1),
  isDeleted: boolean("is_deleted").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ================================
// SETTINGS
// ================================
export const settings = pgTable("settings", {
  id: uuid("id").primaryKey().defaultRandom(),
  settingKey: varchar("setting_key", { length: 100 }).notNull().unique(),
  settingValue: text("setting_value").notNull(),
  isDeleted: boolean("is_deleted").notNull().default(false),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ================================
// PENANDA TANGAN SERTIFIKAT
// ================================
export const signatureSettings = pgTable("signature_settings", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: varchar("name", { length: 255 }).notNull(),
  position: varchar("position", { length: 255 }).notNull(),
  nip: varchar("nip", { length: 30 }),
  signatureImage: varchar("signature_image", { length: 500 }),
  isActive: boolean("is_active").notNull().default(false),
  isDeleted: boolean("is_deleted").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ================================
// PENGATURAN NOMOR SURAT & LOG SERTIFIKAT
// ================================
// Multi-row table:
// - isConfig = true  => baris konfigurasi (format settings)
// - isConfig = false => baris log nomor sertifikat yang diterbitkan
export const certificateNumberSettings = pgTable(
  "certificate_number_settings",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    // === Data nomor sertifikat (hanya untuk isConfig = false) ===
    certificateNumber: integer("certificate_number"),
    certificateCode: varchar("certificate_code", { length: 255 }),
    registrationId: text("registration_id"),
    seminarId: text("seminar_id"),
    monthRoman: varchar("month_roman", { length: 10 }),

    // === Flag pembeda ===
    isConfig: boolean("is_config").notNull().default(false),

    // === Konfigurasi format (snapshot untuk semua baris) ===
    letterPrefix: varchar("letter_prefix", { length: 50 })
      .notNull()
      .default("NO : "),
    institutionCode: varchar("institution_code", { length: 100 })
      .notNull()
      .default("RSUD"),
    letterType: varchar("letter_type", { length: 20 })
      .notNull()
      .default("KET"),
    unitCode: varchar("unit_code", { length: 50 })
      .notNull()
      .default("IV.6.AU"),
    classification: varchar("classification", { length: 10 })
      .notNull()
      .default("A"),
    year: varchar("year", { length: 4 }).notNull(),
    format: varchar("format", { length: 100 })
      .notNull()
      .default("{prefix}{nomor}/{kode}/{bulan}/{tahun}"),
    participantName: varchar("participant_name", { length: 255 }).notNull().default(""),

    // === Override awal penomoran (opsional, hanya di config row) ===
    nextCertificateNumber: integer("next_certificate_number"),

    // === Perilaku reset ===
    resetOption: varchar("reset_option", { length: 20 }).notNull().default("per_tahun"),

    // === Metadata ===
    isDeleted: boolean("is_deleted").notNull().default(false),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
);
